increment14-delete urls
maxsnegir/url-shortener pull request #19
Opened 2022-12-16 13:40 UTC by maxsnegir

2022-12-18 09:48 UTC, shmel1k requested changes

2022-12-18 09:48 UTC, shmel1k commented on internal/handlers/url_handler.go
> +	}
Там же массив строчек в JSONe на вход приходит. Зачем такая машинерия?

2022-12-18 09:48 UTC, shmel1k commented on internal/handlers/url_handler.go
> +			h.JSONResponse(w, http.StatusAccepted, nil)
А как в код `GetUserURLs` пролез метод DeleteURLs? Не лучше ли сделать отдельный хендлер?

Я бы лично не ожидал, что метод Get может быть модифицирующим

2022-12-18 09:48 UTC, shmel1k commented on internal/services/shotener.go
> +	_ = s.storage.DeleteURLs(ctx, urlsToDelete)
Лучше не игнорировать ошибку

2022-12-18 09:48 UTC, shmel1k commented on internal/handlers/url_handler.go
> +			go h.shortener.DeleteURLs(urlChan)
В этом канале, на самом деле, нет смысла. По сути, канал использован в качестве слайса под строки.

Здесь лучше или внутри репозитория использовать канал, который набивать в хендлере, или как-то по-другому

2022-12-18 09:48 UTC, shmel1k commented on internal/services/shotener.go
> +	URL, err := url.Parse(shortURL)
лучше `u, err := ...`

2022-12-18 09:48 UTC, shmel1k commented on internal/services/shotener.go
> +}
Можно чуточку оптимизировать: переписать на линейный поиск последнего слеша и вернуть всё, чтопосле него

2022-12-18 09:48 UTC, shmel1k commented on internal/storage/url_storage.go
> +	return nil
К сожалению, это не очень эффективно по времени.

Можно просто сделать `Update X Set deleted = true WHERE id = ?`

2022-12-18 09:49 UTC, shmel1k requested changes

2022-12-18 09:49 UTC, shmel1k commented on internal/handlers/handlers_enpoint_test.go
> +	"time"
goimports поехал

2022-12-18 09:49 UTC, shmel1k commented on cmd/shortener/main.go
> +	if err = urlStorage.Shutdown(ctx); err != nil {
А зачем так?..

2022-12-19 14:13 UTC, maxsnegir commented on internal/handlers/url_handler.go
> +	}
Да косяк, что-то намудрил

2022-12-19 14:16 UTC, maxsnegir commented on internal/storage/url_storage.go
> +	return nil
Привет, этот кусок кода работает, только когда наш сторадж это хранилище в памяти. 
А такой sql запрос у меня в /internal/storage/postgers_storage, метод DeleteURLs

2022-12-19 14:20 UTC, maxsnegir commented on cmd/shortener/main.go
> +	if err = urlStorage.Shutdown(ctx); err != nil {
Не понял вопроса ( 
тесты не дожидаются завершения работы, приходится ставить sleep

2022-12-19 18:21 UTC, shmel1k requested changes

2022-12-19 18:21 UTC, shmel1k commented on cmd/shortener/main.go
> +	if err = urlStorage.Shutdown(ctx); err != nil {
В новой версии тестов исправлено. Рекомендую выпилить

2022-12-19 18:21 UTC, shmel1k commented on internal/storage/url_storage.go
>  type URLStorage struct {
Я не смог разобраться, чем URLStorage отличается от MapStorage и так далее. Нужно более говорящее название

2022-12-19 18:21 UTC, shmel1k commented on internal/storage/postgres_storage.go
> +			return ps.db.Close()
Я правильно понимаю, тчо в случае, если контекст по какой-то причине будет завершён ранее, то база не будет потушена?

2022-12-19 18:21 UTC, shmel1k commented on internal/handlers/url_handler.go
> +		go h.shortener.DeleteURLs(urlIDsToDel)
Здесь потеряна основная идея задания: отдельный канал, в который будут набиваться урлы. Здесь просто передаётся массив(что тоже имеет смысл, но не совпадает с идеей задания)

2022-12-20 19:38 UTC, closed without merging